config/routes.rb
Bns::Application.routes.draw do
  resources :articles

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  devise_for :users, :skip => [:registrations], :controllers => { :confirmations => "confirmations" }

  namespace :admin do
    root :to => 'home#index'
    resources :fabrics
    resources :accessories
    resources :articles, :except => [:new,:destroy] do
      post 'preview', :on => :collection
    end
    resources :users
    resources :shops do
      get 'day_measures', :on => :member
    end
    post 'shop_measure_setbusy' => "shop_measure#set_busy"
    post 'shop_measure_set_username' => "shop_measure#set_username"
  end

  namespace :buy do
    %w(suit jacket trousers shirt coat).each do |cloth|
      get "#{cloth}(/:step)" => "#{cloth}#index", :as => "#{cloth}"
      get "select_#{cloth}_fabric/:id" => "#{cloth}#select_fabric"
      post "select_#{cloth}_design" => "#{cloth}#select_design"
    end
  end

  get "about" => "home#about"
  get "profile" => "home#profile"
  get "shop" => "shop#index"
  get "shop/sizing_table" => "shop#sizing_table"
  post "shop/book_hour" => "shop#book_hour"
  get "faq" => "home#faq"
  get "gift_certificates" => "home#gift_certificates"
  get "quality_guarantee" => "home#quality_guarantee"
  get "material" => "home#material"
  get "process" => "home#process"
  get "buy_online" => "home#buy_online"

  get "content/:p1(/:p2)" => "home#content"

  root :to => 'home#index'

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :address, :time, :phone, :title, :description, :map, :remove_map, :map_cache
  validates :title, :presence => true, :uniqueness => true
  has_many :shop_measures, :dependent => :delete_all
  mount_uploader :map, MapUploader
end

app/controllers/admin/shops_controller.rb
# encoding: utf-8

class Admin::ShopsController < ApplicationController
  #before_filter :authenticate_user!
  layout "admin"

  def day_measures
    #@shop = Shop.find(params[:id])
    #@shop.day_measures
    @date = params[:date].to_date
    mysql_date = @date.strftime('%Y-%m-%d')
    measures = ShopMeasure.all :conditions => [ 'shop_id = ? AND DATE(at) = ?', params[:id], mysql_date ]
    by_hour = Hash[ measures.map { |obj| [obj.at.hour, obj] } ]
    @measures = []
    ShopMeasure.transaction do
      (10..21).each do |h|
        measure = by_hour[h]
        if !measure
          at = @date.to_datetime.change({:hour => h , :min => 0 , :sec => 0 })
          measure = ShopMeasure.new(:at => at, :isbusy => true, :shop_id => params[:id])
          measure.save!(:validate => false)
        end
        @measures.push measure
      end
    end
    render :layout => false
  end

  def index
    @shops = Shop.all
  end

  # GET /admin/shops/new
  # GET /admin/shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /admin/shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /admin/shops
  # POST /admin/shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to admin_shops_path, notice: 'Магазин успешно добавлен.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/shops/1
  # PUT /admin/shops/1.json
  def update
    @shop = Shop.find(params[:id])


    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        #if to_filename = upload_file(params[:shop][:file], @shop.id)
        #  @shop.update_column(:mapfilename, to_filename)
        #end
        format.html { redirect_to admin_shops_path, notice: 'Магазин успешно обновлен.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/shops/1
  # DELETE /admin/shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to admin_shops_url, notice: 'Магазин успешно удален.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:book_hour]
  #before_filter :authenticate_user!, :only => [:book_hour]

  def index
    # TODO: implement shop selector
    @shop = Shop.first || Shop.new(title: "No shops found in database")
  end

  def book_hour
    at = DateTime.strptime("#{params[:date]} #{params[:hour]}", '%Y-%m-%d %H')
    measure = ShopMeasure.where(:at => at, :shop_id => params[:id]).first_or_initialize
    measure.update_attributes(params[:book])
    measure.isbusy = true
    if user_signed_in?
      measure.user_id = current_user.id
    end
    if measure.save
      render json: { :status => 'ok', :id => "td_#{at.to_date}_#{at.hour}" }
    else
      render json: measure.errors, status: :unprocessable_entity
    end
  end

  def sizing_table
    @shop_id = params[:id].to_i
    @date_start = Date.strptime("#{params[:year]} #{params[:week]}", '%Y %W')
    @date_end = @date_start.end_of_week
    measures = ShopMeasure.where(
      [ 'shop_id = ? AND DATE(at) >= ? AND DATE(at) <= ?', @shop_id ] +
      [ @date_start, @date_end ].map { |d| d.strftime('%Y-%m-%d') })
      .order('at')
      .limit(120)
    @by_dayhour = Hash[ measures.map { |obj| [obj.at.wday.to_s + '_' + obj.at.hour.to_s, obj] } ]
    @time_range = 10..21
    render :layout => false
  end
end

app/views/admin/shops/_form.html.haml
%h1= @shop.title || 'новый магазин'
%br
.shop_info
  .u_subtitle Информация о магазине
  =form_for [:admin,@shop] do |f|
    -@shop.errors.full_messages.each do |msg|
      %li= msg
    %dl
      %dt
        %label Название
      %dd
        =f.text_field :title, :class => 'search-field', :onfocus => 'this.className="selected"', :onblur => 'this.className="search-field"', :tabindex => "1"
    %dl
      %dt
        %label Адрес
      %dd
        =f.text_area :address, :class => 'search-field', :onfocus => 'this.className="selected"', :onblur => 'this.className="search-field"', :tabindex => "2", :rows => 2
    %dl
      %dt
        %label Время работы
      %dd
        =f.text_area :time, :class => 'search-field', :onfocus => 'this.className="selected"', :onblur => 'this.className="search-field"', :tabindex => "3"
    %dl
      %dt
        %label Описание
      %dd
        =f.text_area :description, :class => 'search-field', :onfocus => 'this.className="selected"', :onblur => 'this.className="search-field"', :tabindex => "4", :rows => 10
    %dl
      %dt
        %label Изображение карты
      %dd
        =f.file_field :map, :class => 'search-field', :onfocus => 'this.className="selected"', :onblur => 'this.className="search-field"', :tabindex => "5"
        =f.hidden_field :map_cache
    -if @shop.map?
      %dl
        %dt
          %label Удалить
        %dd
          =f.check_box :remove_map
          =image_tag(@shop.map_url)
    %dl
      %dt
        %label Телефон
      %dd
        =f.text_field :phone, :class => 'search-field', :onfocus => 'this.className="selected"', :onblur => 'this.className="search-field"', :tabindex => "4"
    .submit_btn
      =f.submit :value => 'сохранить', :tabindex => "5", :disable_with => 'сохранить'
    -unless @shop.new_record?
      .shop_delete
        =link_to 'Удалить позицию', admin_shop_path(@shop), :method => :delete, :confirm => 'Точно удалить?'
-unless @shop.new_record?
  .shop_calendar
    .u_subtitle Время приема на снятие мерок
    #datepicker1
  .shop_calendar_info

app/views/admin/shops/day_measures.html.haml
:javascript
  function go_next_date(date) {
    $('#datepicker1').datepicker('setDate', date);
    load_measures(date)
    return false
  }

.month
  %a.m_arrow_left{:href => "#", :onclick => "return go_next_date('#{l @date - 1.day}')" }
  =l @date, :format => :short
  %a.m_arrow_right{:href => "#", :onclick => "return go_next_date('#{l @date + 1.day}')" }
- @measures.each do |m|
  .select_time.enabled
    .datatime= "%02i:00 - %02i:00" % [m.at.hour,m.at.hour+1]
    .u_options
      =link_to 'свободно', admin_shop_measure_setbusy_path(:id => m.id, :busy => false), :remote => true, :method => :post, :class => m.isbusy ? '' : 'u_active_link'
      =link_to 'забронировано', admin_shop_measure_setbusy_path(:id => m.id, :busy => true), :remote => true, :method => :post, :class => m.isbusy ? 'u_active_link' : ''
    .time_client{ :style => m.user_name && m.isbusy ? '' : 'display:none' }
      Клиент:
      %a{:href => "#" , :onclick => "$(this).closest('.select_time').find('.time_client').hide(); $(this).closest('.select_time').find('.input_client').show();", :title => "#{m.user_name}, #{m.phone}" }= m.user_name
    =form_tag admin_shop_measure_set_username_path, :remote => true,:style => 'display: inline' do
      .input_client{ :style => !m.user_name && m.isbusy ? '' : 'display:none' }
        =hidden_field_tag :id, m.id
        %input{:name => "user_name", :type => "text", :id => "shop_client#{m.id}", :class => 'search-field',
          :value => "#{m.user_name || 'Введите имя или e-mail'}",
          :onfocus => 'if (this.value=="Введите имя или e-mail") {this.value=""; this.className="selected"}',
          :onblur => 'if (this.value=="") {this.value="Введите имя или e-mail"; this.className="search-field";}'}
        %a{:href => "", :onclick => "if ($(this).prev().val()=='Введите имя или e-mail') {$(this).prev().val('').addClass('selected')}; $(this).closest('form').submit(); return false" } добавить

app/views/admin/shops/edit.html.haml
=content_for :head do
  :javascript
    function load_measures(date) {
      $.get('#{day_measures_admin_shop_path(@shop)}', { date: date }, function (data) {
        $('.shop_calendar_info').html(data)
      })
    }

    jQuery(document).ready(function(){
      $('#datepicker1' ).datepicker({ onSelect: load_measures })
      //$('#datepicker1').datepicker('option', $.datepicker.regional[ "ru" ])
      $('#datepicker1').datepicker('option', 'changeYear', false)
    })
=render 'form'

app/views/admin/shops/index.html.haml
%h1 Список магазинов
%br
/ // CONTENT
-@shops.each do |shop|
  .shop_list
    .u_subtitle= shop.title
    %a.shop_list_edit{:href => "#{edit_admin_shop_path(shop)}"} Редактировать информацию и время приема на снятие мерок
    .sl_descr
      %p= shop.address
      %br/
      %p Тел.: #{shop.phone}
-if @shops.size == 0 # временно, пока только дин магазин
  %a.sl_add{:href => "#{new_admin_shop_path}"} Добавить магазин

app/views/admin/shops/new.html.haml
=render 'form'