config/routes.rb
Bns::Application.routes.draw do
  resources :articles

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  devise_for :users, :skip => [:registrations], :controllers => { :confirmations => "confirmations" }

  namespace :admin do
    root :to => 'home#index'
    resources :fabrics
    resources :accessories
    resources :articles, :except => [:new,:destroy] do
      post 'preview', :on => :collection
    end
    resources :users
    resources :shops do
      get 'day_measures', :on => :member
    end
    post 'shop_measure_setbusy' => "shop_measure#set_busy"
    post 'shop_measure_set_username' => "shop_measure#set_username"
  end

  namespace :buy do
    %w(suit jacket trousers shirt coat).each do |cloth|
      get "#{cloth}(/:step)" => "#{cloth}#index", :as => "#{cloth}"
      get "select_#{cloth}_fabric/:id" => "#{cloth}#select_fabric"
      post "select_#{cloth}_design" => "#{cloth}#select_design"
    end
  end

  get "about" => "home#about"
  get "profile" => "home#profile"
  get "shop" => "shop#index"
  get "shop/sizing_table" => "shop#sizing_table"
  post "shop/book_hour" => "shop#book_hour"
  get "faq" => "home#faq"
  get "gift_certificates" => "home#gift_certificates"
  get "quality_guarantee" => "home#quality_guarantee"
  get "material" => "home#material"
  get "process" => "home#process"
  get "buy_online" => "home#buy_online"

  get "content/:p1(/:p2)" => "home#content"

  root :to => 'home#index'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  #before_filter :authenticate_user!
  layout "admin"

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def gift_certificates
  end

  def faq
  end

  def quality_guarantee
  end

  def material
  end

  def content
    path = [params[:p1], params[:p2]] * '-'
    @article = Article.find_by_path(path)
    @article ||= Article.new(:path => path, :content => 'Coming soon..')
  end
end

app/views/home/about.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
-#.menu
  %a.active{:href => "#"} о компании
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        %h1 о компании
        =image_tag "img1.jpg"
        %br/
        %br/
        %p Наша компания основана в 2011 году двумя выходцами из Стратегического консалтинга.
        %p Увидев все более явно формирующуюся рыночную нишу на Российском рынке классической мужской одежды, мы решили выстроить свой сервис по пошиву недорогой кастомизированной одежды для мужчин.
        %p Чтобы наш сервис оказался успешным мы пострались взять лучшее от западных аналогов и добавить понимание российской специфики. При этом постоянно модифицируя и подстраивая его под нужды нашей целевой аудитории.
        %p
          Выстраивая компанию мы решили опираться на следующие  основными ценностями
        %ul{ :style => 'list-style: disc; list-style-position: inside' }
          %li Высокое качество
          %li Идеальный стиль
          %li Удобство и комфорт
        %p Все это при оптимальном соотношении value for money
    .dragger_container
      .dragger

app/views/home/buy_online.html.haml
- content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "assets/slides/slide3.jpg"}
.buy_online
  %table
    %tr
      %td.suit{:rowspan => "2"}
        %a{:href => buy_suit_path }
          %img{:alt => "", :src => "assets/buy/1.jpg"}/
      %td.coat
        %a{:href => buy_jacket_path}
          %img{:alt => "", :src => "assets/buy/2.jpg"}/
      %td.coat
        %a{:href => buy_shirt_path}
          %img{:alt => "", :src => "assets/buy/3.jpg"}/
      %td.suit{:rowspan => "2"}
        %a{:href => "#"}
          %img{:alt => "", :src => "assets/buy/4.jpg"}/
    %tr
      %td.coat
        %a{:href => buy_trousers_path}
          %img{:alt => "", :src => "assets/buy/5.jpg"}/
      %td.coat
        %a{:href => buy_coat_path}
          %img{:alt => "", :src => "assets/buy/6.jpg"}/
#mcs3_container{:style => "display:none;"}
  .customScrollBox
    .container
      .content
    .dragger_container
      .dragger

app/views/home/content.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
.menu
  - @article.submenu.each do |path, title|
    - p1, p2 = path.split('-')
    - t1, t2 = title.split(' - ')
    %a{:href => "#{url_for(:p1 => p1, :p2 => p2)}", :class => path == @article.path ? 'active' : '' }= t2
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        = @article.content.html_safe
    .dragger_container
      .dragger

app/views/home/design.html.erb
<% content_for :bg_slide do %>
  <img src="assets/slides/slide3.jpg" alt="" id="bgimg">
<% end %>

<!-- // CONTENT -->
  <div class="menu">
        <div class="menu_design"> - пиджак</div>
        <div class="submenu_design">
          <a href="#" class="step_done">Ткань</a>
        </div>
        <div class="submenu_design">
          <a href="#">Дизайн</a>
          <div class="submenu_design_block ttnone">
            <p><span>Кол-во пуговиц:</span> 2</p>
            <p><span>Пошив:</span> Классический</p>
            <p><span>Форма лацкана:</span> Пилообразный</p>
            <p><span>Форма карманов:</span> Прямые</p>
            <p><span>Манжеты: </span> Рабочие</p>
            <p><span>Кол-во шлиц: </span>Ни одной</p>
            <p><span>Монограмма: </span>Да</p>
            <p><span>Текст монограммы: </span>B&S</p>
            <p><span>Цвет монограммы: </span>Светло-зеленый (№TH022)</p>
            <p><span>Декоративная прострочка лацканов и пиджака: </span>В цвет пиджака</p>
            <p><span>Цвет прострочки отверстий для пуговиц:</span> Темно-синий (№TH005)</p>
            <p><span>Выбор пуговиц: </span>Темно-коричневые (Button 003)</p>
          </div>
        </div>
        <div class="submenu_design">
          <a href="#">Размер</a>
          <div style="display:none;" class="submenu_design_block">
            <span>основная</span>
            <img src="/assets/buy/small1.jpg" class="submenu_d_img active_d" alt="">
            <div class="submenu_d">
              <p>Deep Blue Nailhead</p>
              <p class="submenu_d_price">
                19 300
                <span class="rur">
                  p
                  <span>уб.</span>
                </span>
              </p>
            </div>
            <span>подкладка</span>
            <img src="/assets/white_img.jpg" class="submenu_d_img" alt="">
            <div class="submenu_d">
              <p>Deep Blue Nailhead</p>
              <p class="submenu_d_price">
                19 300
                <span class="rur">
                  p
                  <span>уб.</span>
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>

  
  <div id="mcs3_container" class="full_window">
    <div class="customScrollBox">
      <div class="container">
      <!-- content block -->
        <div class="content">
            <form>
              <h1>Выбор дизайна пиджака</h1>
              <div class="sort_by">
                <div class="sort_options">
                  <a href="#" class="field1 u_active_link">вид спереди</a>          
                  <a href="#" class="field2">вид сзади</a>
                </div>
              </div>


              <table class="options_table">
                <tr>
                  <td><img src="/assets/buy/suit/default.png" alt="" /></td>
                  <td>
                    <div class="main_options">
                      <div class="menu_design">ОСНОВНЫЕ ОПЦИИ</div>



                      <div class="options_item">
                        <p>Кол-во пуговиц</p>
                        <div class="lineForm3">
                          <select id="options_item1" tabindex="2">
                            <option value="">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Пошив</p>
                        <div class="lineForm3">
                          <select id="options_item2" tabindex="2">
                            <option value="">Классический 1</option>
                            <option value="2">Классический 2</option>
                            <option value="3">Классический 3</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Форма лацкана</p>
                        <div class="lineForm3">
                          <select id="options_item3" tabindex="2">
                            <option value="">Пилообразный 1</option>
                            <option value="2">Пилообразный 2</option>
                            <option value="3">Пилообразный 3</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Форма карманов</p>
                        <div class="lineForm3">
                          <select id="options_item4" tabindex="2">
                            <option value="">Прямые 1</option>
                            <option value="2">Прямые 2</option>
                            <option value="3">Прямые 3</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Дополнительный карман</p>
                        <div class="lineForm3">
                          <select id="options_item5" tabindex="2">
                            <option value="">Да</option>
                            <option value="2">Нет</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>

                      <div class="options_item">
                        <p>Манжеты</p>
                        <div class="lineForm3">
                          <select id="options_item6" tabindex="2">
                            <option value="">Рабочие 1</option>
                            <option value="2">Рабочие 2</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Кол-во шлиц</p>
                        <div class="lineForm3">
                          <select id="options_item7" tabindex="2">
                            <option value="">Ни одной 1</option>
                            <option value="2">Ни одной 2</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Монограмма</p>
                        <div class="lineForm3">
                          <select id="options_item8" tabindex="2">
                            <option value="">Да</option>
                            <option value="2">Нет</option>
                          </select>
                        </div>
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>


                      <div class="options_item">
                        <p>Текст монограммы (только английские буквы)</p>
                        <input type="text" />
                        <a href="/" class="sort_link"><img src="/assets/hint.png" alt="" /></a>
                      </div>






                    </div>
                    <div class="decor_options">
                      <div class="menu_design">ДЕКОРАТИВНЫЕ<br />ОПЦИИ</div>

                      <div class="options_item">
                        <a href="/" class="sort_link2"><img src="/assets/hint.png" alt="" /></a>
                        <p>Декоративная прострочка лацканов и пиджака</p>
                        <img src="/assets/buy/options_default.png" alt="">
                        <div class="submenu_decor">
                          <p>в цвет пиджака</p>
                          <a href="/">изменить</a>
                        </div>

                        
                      </div>

                      <div class="options_item">
                        <a href="/" class="sort_link2"><img src="/assets/hint.png" alt="" /></a>
                        <p>Цвет прострочки отверстий для пуговиц</p>
                        <img src="/assets/buy/options_default.png" alt="">
                        <div class="submenu_decor">
                          <p>Темно синий</p>
                          <a href="/">изменить</a>
                        </div>

                        
                      </div>

                      <div class="options_item">
                        <a href="/" class="sort_link2"><img src="/assets/hint.png" alt="" /></a>
                        <p>Выбор пуговиц</p>
                        <img src="/assets/buy/options_default.png" alt="">
                        <div class="submenu_decor">
                          <p>темно-коричневые</p>
                          <a href="/">изменить</a>
                        </div>

                        
                      </div>

                      <div class="options_item">
                        <a href="/" class="sort_link2"><img src="/assets/hint.png" alt="" /></a>
                        <p>Цвет ткани подклакди под воротник</p>
                        <img src="/assets/buy/options_default.png" alt="">
                        <div class="submenu_decor">
                          <p>Blue Nailhead</p>
                          <a href="/">изменить</a>
                        </div>

                        
                      </div>

















                    </div>
                    


                  </td>
                </tr>







              </table>




              
              
              
        
        
         
   

        </form>
        </div> <!-- content -->
      </div> <!-- container -->
      


      <div class="dragger_container">
        <div class="dragger"></div>
      </div>
    </div>
  </div>
  <!-- CONTENT // -->

app/views/home/faq.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
.menu
  %a{:href => "#{process_path}"} описание процесса
  %a{:href => "#{quality_guarantee_path}"} гарантии качества
  %a{:href => "#{material_path}"} ткани
  %a.active{:href => "#{faq_path}"} f.a.q.
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        %h1 f.a.q.
        %a.hover_list.l1{:href => "#"} Как происходит оплата
        .hover_content1
          %p
            Наша продкуция изготавливается по Вашим индивидуальным меркам, поэтому мы вынуждены брать предоплату не менее 75% при заказе  костюма и не менее 90% при заказе сорочку. Данная предоплата позволяет покрыть нам производственные затраты, в случае, если Вы по необъективным причинам откажитесь от готового продукта.
        %a.hover_list.l2{:href => "#"} Что будет, если костюм / рубашка не подошли
        .hover_content2
          %p
            Костюм и сорочка изготовленные по индивидуальным меркам это продукт часто ручного труда и, естественно, при этом могут возникать неточности, которые в итоге приводят к ошибкам при посадке готового изделия на Вас. Поэтому в первую очередь мы попытаемся исправить эти неточности при помощи нашего портного, который постоянно находиться в нашем магазине и максимально оперативно сможет определить неточности посадки и, в зависимости, от комлексности требуемых доработок, максимально приблизить Ваш костюм к идельаному. Если это не представляется возможным, и ошибка нашей компании очевидна. Мы, извинившись, беремся полностью компенсировать стоимость Вашего костюма
        %a.hover_list.l3{:href => "#"} Как быстро изготавливается костюм/ сорочка
        .hover_content3
          %p
            В данный момент, ввиду необходимости ввозить нашу продукцию через границу мы готовы взять на себя обязательство укладываться при каждом заказе в 4 недели, которых нам будет достаточно, чтобы привести Вашу костюм или сорочку к нам в магазин.
        %a.hover_list.l4{:href => "#"} Зачем нужна запись на примерку
        .hover_content4
          %p
            Мы ненавидим стоять в очередях и находиться в тестных помещениях, если, конечно, Вас не окружают молодые красивые девушки на какой-либо шумной вечеринке, поэтому мы постарались устроить наш сервис максимальноэто удобным и комфортым для Вас. На данный момент это реализовано при помощи записи через наш сайт или по телефону. В дальнешем мы обещаем также создавать тесное кольцо красоток в любое время, когда Вам захочется приехать к нам в магазин
        %a.hover_list.l5{:href => "#"} Если я не нашел подходящей ткани, значит ли, что мне придется искать другую компанию
        .hover_content5
          %p
            В первую очередь мы будем очень благодарны Вам если Вы нам сообщит какую ткань Вам не удалось найти. Дело в том, что мы стараемся управлять своими стоками с учетом пожеланий рынка, поэтому если мы и не сможем что-то предложить сейчас мы обязательно постараемся предложить это в ближайшей перспективе. Кроме этого, если Вы не нашли этого на сайте, возможно данная ткань может быть у нас в магазине. Каждый сезон компании-производители тканей выпускают сезонные коллекции, возможно мы не успели обновить ассортимент на сайте, поэтому большая просьба связаться с нами и уточнить, будут ли вскоре обновления ассортимента. Возможно среди новых тканей будет именна та, которую Вы ищите.
        %a.hover_list.l6{:href => "#"} Почему Вы пропогандируете холостяцкий образ жизни
        .hover_content6
          %p
            Мы считаем, что настоящий мужчина должен быть, в первую очередь, свободным человеком. Во вторую, мы сами являемся искателями приключений. Обремененные отношениями, а тем более самой тяжелой их формой, получать максимальный драйв от жизни возможно только при самом удачном стечении обстоятельств и самом правильном выбооре партнера. Так везет далеко не всем. Кроме этого Мы должны добиваться в жизни значимых результатов не только в личной жизни. Родить и воспитать ребенка на каком-то уровне могут многие.
          %p
            Добиться успеха в карьере и бизнесе уже не так просто и, критически важно, вступая в отношения Вы привязываете себе огромную гирю. Поэтому тут важно НЕ СПЕШИТЬ! Важно попробовать и выбрать из большого количества наций, ростов, цветов кожи, волос, глаз, различного склада характера, безусловно высокой интеллектуалки и при этом не дающей Вам заскучать в постели и не только в постели, во всем доме, в парке, самолете, море, в офисе, машине. Ищите свой идеал, не сдавайтесь, только тогда Вы будете оставаться мужчиной, примером для подражания и объектом зависти. Тоже мы относим и к женщинам! Мы современные люди и толеранты к противоположному полу, ищите, исследуйте мужчин, перепробуйте всех своих знакомых и остановитесь, если будете абсолютно, совершенно, уверены, только так Вы оба найдете друг друга. И не расстраивайтесь, если в 30 вы его не встретили, это лучше развода в 40, тем более с детьми. Вкратце, хотите беззаботно жить, хотите красивую умную жену, заботливого внимательного мужа, счастливых успешных детей - до 7-го миллиона, либо 40 лет KEEP ON TRYING.
    .dragger_container
      .dragger

app/views/home/gift_certificates.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
.menu
  %a{:href => "#"} цены
  %a.active{:href => "#"} подарочные сертификаты
  %a{:href => "#"} скидки
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        %h1 подарочные сертификаты
        =image_tag "sertificate.jpg"
        %br/
        %br/
        %p
          Мы знаем как сложно иногда подарить что-то интересное, практичное и, при этом, что должно прийтись на вкус одариваемому мужчине. Поэтому в нашей компании мы приняли решение ввести инструмент подарочных карт, который любой мужчина сможет использовать для оплаты товаров из нашего ассортимента. Ведь индивидуально скроеная рубашка или костюм – это всегда уместный подарок, обладающий практичностью, идеальной «подходимостью» как по стилю, так и по размерам. Любому мужчине такой подарок доставит искренне удовольствие при его использовании. На данный момент мы предлагаем три вида подарочных сертификатов – на 2 000, 5 000 и 10 000 руб.
    .dragger_container
      .dragger

app/views/home/material.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
.menu
  %a{:href => "#{process_path}"} описание процесса
  %a{:href => "#{quality_guarantee_path}"} гарантии качества
  %a.active{:href => "#{material_path}"} ткани
  %a{:href => "#{faq_path}"} f.a.q.
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        %h1 Ткани
        %p
          %b Ткани
          – это сырье для нашей продукции. Как и везде сырье определяет уровень конечного продукта. И является недостаточным, но при этом обязательным, условием получения качественного продукта. Поэтому мы решили посвятить отдельный раздел нашего сайта нашему сырью.
        %p
          %b В первую очередь мы минимизировали (не приемлим)
          использование смесовых тканей до их нишевого применения – командировки. Свойства смесовых тканей позволяют хорошо переносить самые жесткие условия перевозок, захотите ли ненадолго прилечь в аэропорту пересадки или Вам сложно находиться в одном положении в кресле самолета. Трение и сильное натяжение, в таких условиях смесовые ткани продержаться дольше. На жаргоне из называют «пуленепробиваемые».
        %p
          %b Для тех кто не приемлит послаблений в своем внешнем виде
          даже на короткое время подойдут только натуральные ткани, которые являются основной нашей коллекции. Только такое сырье позволяет Вашей одежде выглядеть лучшим образом.
        %p
          %b Рассматривая более детально
          ткани для костюма в нашей коллекции изготовлены из шерсти. Основные отличия состоят в кручении шерсти и плотности полотна. Кручение ткани, обозначаемое как xxx’S, означает длину нити, номинированную в м, которую можно получить из 1 кг шерсти. Таким образом, чем выше кручение, тем тоньше нить, тем более нежным, но при этом хрупким, становиться тканое полотно. Поэтому для ежедневного ношения рекомендуется использовать ткани кручения 130’S – 150’S, в этих тканях показатель «нежности» и «хрупкости» находиться в оптимальном соотношении. При этом ткани более высокго кручения подойдут для костюмов, которые Вы будете одевать реже, на вечеринки, в отпуск. По ощущениям ткань кручения 180’S начинает напоминать плотный шелк, при этом сохраняя все самые важные характеристики шерсти.
        %p
          %b В нашем ассортименте шерстяные ткани закупаются
          только в Италии. Это позволяет получать гарантированно высокое качество полотна, а также самые новые трендовые дизайны. Для премиальной линейки мы используем ткани известного мирового бренда – Loro Piana.
        %p
          %b Хлопковые ткани
          закупаются в регионах мира, где хлопок произрастает – это Китай и Египет.
        %p
          %b Ассортимент наших тканей Вы можете
          оценить зайдя на старинцу конструктора или приехва к нам в магазин.
    .dragger_container
      .dragger

app/views/home/process.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
.menu
  %a.active{:href => "#{process_path}"} описание процесса
  %a{:href => "#{quality_guarantee_path}"} гарантии качества
  %a{:href => "#{material_path}"} ткани
  %a{:href => "#{faq_path}"} f.a.q.
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        %h1 описание процесса
        %p
          В нашей модели мы постарались сделать процесс наиболее простым, быстрым и удобным. Мужской костюм на заказа - продукт достаточно сложный, поэтому, делая заказ в первый раз, потребует от Вас некоторых временных затрат. Последющие заказы будет делать значительно проще.
        .sep
        %a.hover_list.l1{:href => "#"} ПРОЦЕСС ЗАКАЗА КОСТЮМА В ПЕРВЫЙ РАЗ
        .hover_content7
          %p.circle_one
            Конструируете нужный Вам дизайн на нашем сайте или приезжайте сразу в магазин;
          %p.circle_two
            %span
              Записываетесь в магазин на примерку;
          %p.circle_three
            %span
              Наш специалист снимет мерки;
          %p.circle_four
            %span
              Оплачиваете товар и ждёте оповещения по e-mail (до 4-ёх недель);
          %p.circle_five
            После оповещения приезжаете к нам в магазин для повторной примерки готового костюма;
          %p.circle_six
            Если требуются дополнительные корректировки, за 1-у неделю мы дорабатываем Ваш костюм.
        %a.hover_list.l2{:href => "#"} Заказ костюма во второй раз
        .hover_content8
          %p.circle_one
            Конструируете нужный Вам дизайн на нашем сайте или приезжайте сразу в магазин;
          %p.circle_two
            Выбираете существующий профиль размеров или вновь записываетесь в наш магазин на примерку;
          %p.circle_three
            %span
              Оплачиваете товар и ждёте оповещения по e-mail (до 4-ёх недель);
          %p.circle_four
            %span
              После оповещения приезжаете к нам в магазин за готовым костюмом.
        %a.hover_list.l3{:href => "#"} заказ рубашки впервые
        .hover_content9
          %p.circle_one
            Конструируете нужный Вам дизайн на нашем сайте или приезжайте сразу в магазин;
          %p.circle_two
            Снимаете мерки самостоятельно пользуясь нашими подсказками на сайте или записываетесь в наш магазин на примерку со специалистом;
          %p.circle_three
            %span
              Оплачиваете товар и ждёте оповещения по e-mail (до 4-ёх недель);
          %p.circle_four
            %span
              Выбираете способ доставки.
        %a.hover_list.l4{:href => "#"} заказ рубашки во второй раз
        .hover_content10
          %p.circle_one
            Конструируете нужный Вам дизайн на нашем сайте или приезжайте сразу в магазин;
          %p.circle_two
            Выбираете существующий профиль размеров или создаёте новый профиль самостоятельно, либо с помощью специалиста в магазине;
          %p.circle_three
            %span
              Оплачиваете товар и ждёте оповещения по e-mail (до 4-ёх недель);
          %p.circle_four
            %span
              Выбираете способ доставки.
    .dragger_container
      .dragger

app/views/home/quality_guarantee.html.haml
-content_for :bg_slide do
  %img#bgimg{:alt => "", :src => "#{asset_path('slides/slide4.jpg')}"}/
.menu
  %a{:href => "#{process_path}"} описание процесса
  %a.active{:href => "#{quality_guarantee_path}"} гарантии качества
  %a{:href => "#{material_path}"} ткани
  %a{:href => "#{faq_path}"} f.a.q.
#mcs3_container
  .customScrollBox
    .container
      / content block
      .content
        %h1 гарантии качества
        =image_tag "guaranty_01.jpg"
        %br/
        %br/
        %p
          Качество является одной из самых важных ценностей компании, это отражается и 
          %br/
          на качестве итогового продукта и на качестве оказания услуг. Мы постоянно
          %br/
          работаем над улучшением этих показателей. Получая обратную связь от наших клиентов, мы обращаем внимание на все мелочи, которые вызывают нарекания наших клиентов и пытаемся максимально быстро внедрить изменения. Для того, чтобы достичь текущего уровня мы детально проработали три основных аспекта – это материалы, из которых производится наша продукция. Второе, это производственные мощности, где отшивается весь ассортимент нашей компании. И, третье, не менее важное это персонал, который сопровождает наших клиентов на протяжении всего процесса зримо или незримо.
        %p.block_title Производство
        =image_tag "production.jpg"
        %br/
        %br/
        %p
          Мы отошли от традиционной парадигмы размещения прозводства
          %br/
          в Юго-Восточной Азии и предприняли серьезные усилия, чтобы найти приемлимое по цене производство в Европе. При условии отсутствия Вашего прямого контроля, производители Юго-Восточной Азии, предлагая более низкие цены, не могут выдерживать стабильно высокого уровня качества. Европейским производителям более свойственна отвественность за качество продукта, стремление сохранить хорошие отношения с партнерами и постоянное совершенствование своего производства. Данный подход в значительной мере соответсвтует подходу нашей компании, поэтому именно в Европе отшиваются Ваши костюмы и сорочки.
        %p.block_title Материалы
        =image_tag "guaranty_02.jpg"
        %br/
        %br/
        %p
          Развитие текстильных технологий, стремление производителей максимизировать прибыль и все более частые колебания роста цен на натуральные материалы привело к росту числа смесовых, а иногда и полностью синтетических тканей. Не смотря на кажущюся технологичность таких тканей, они более подходят для
          %br/
          пошива Вашей одежды для горных лыж или дайвинга. Для повседневной жизни в городе лучше натурального хлопка, шерсти, льна и шелка пока ничего нет. Серьезные нагрузки на наш организм требуют создания уютных условий для него, ткань должна дышать. А постоянная смена обстановки – офис, автомобиль, аэропорт, самолет, не должна приводить вашу одежду в лоснящуюся скомканную униформу. В этом смысле натуральные материалы не потеряли своей
          %br/
          актуальности и сегодня.
        %p.block_title Персонал
        =image_tag "staff.jpg"
        %br/
        %br/
        %p
          Мы сервисная компания, а в оказании услуг часто нет ничего важнее
          %br/
          человеческого фактора. Именно поэтому мы обращаем много внимания на профессоинализм наших сотрудников. Мы инвестируем значительные средства, как материальные, так и временные в обучение нашего персонала и постоянное совершествование его навыков.
    .dragger_container
      .dragger