config/routes.rb
Bns::Application.routes.draw do
  resources :articles

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  devise_for :users, :skip => [:registrations], :controllers => { :confirmations => "confirmations" }

  namespace :admin do
    root :to => 'home#index'
    resources :fabrics
    resources :accessories
    resources :articles, :except => [:new,:destroy] do
      post 'preview', :on => :collection
    end
    resources :users
    resources :shops do
      get 'day_measures', :on => :member
    end
    post 'shop_measure_setbusy' => "shop_measure#set_busy"
    post 'shop_measure_set_username' => "shop_measure#set_username"
  end

  namespace :buy do
    %w(suit jacket trousers shirt coat).each do |cloth|
      get "#{cloth}(/:step)" => "#{cloth}#index", :as => "#{cloth}"
      get "select_#{cloth}_fabric/:id" => "#{cloth}#select_fabric"
      post "select_#{cloth}_design" => "#{cloth}#select_design"
    end
  end

  get "about" => "home#about"
  get "profile" => "home#profile"
  get "shop" => "shop#index"
  get "shop/sizing_table" => "shop#sizing_table"
  post "shop/book_hour" => "shop#book_hour"
  get "faq" => "home#faq"
  get "gift_certificates" => "home#gift_certificates"
  get "quality_guarantee" => "home#quality_guarantee"
  get "material" => "home#material"
  get "process" => "home#process"
  get "buy_online" => "home#buy_online"

  get "content/:p1(/:p2)" => "home#content"

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :fio, :phone

  validates :fio, :phone, :presence => true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  #before_filter :authenticate_user!
  layout "admin"

  def index
    @users = []
    @default_limit = 100
    if params[:all]
      @users = User.limit(@default_limit)
    end
    if request.xhr?
      if q = params[:q] and q.length > 1
        # быстрый поиск
        @users = User.where("fio LIKE :qs OR email LIKE :qs", { :qs => "#{q}%" }).limit(15)
      else
        # "показать все"
        limit = params[:l] || @default_limit
        offset = params[:o] || 0
        order = 'id'
        order = params[:user_sort] unless params[:user_sort].blank?
        params[:sort_desc] == '1' and order = "#{order} DESC"
        @users = User.order(order).limit(limit).offset(offset)
      end
      render :layout => false,
        :partial => 'admin/users/searchresults',
        :locals => { :users => @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @admin_user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @admin_user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(params[:admin_user])

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render json: @admin_user, status: :created, location: @admin_user }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @admin_user = User.find(params[:id])

    respond_to do |format|
      if @admin_user.update_attributes(params[:admin_user])
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/_searchresults.html.haml
-users.each do |user|
  %tr{"data-href" => "#{admin_user_path(user)}" }
    %td.user_cel= user.fio
    %td{:style => 'color: rgb(0,0,0)'}= user.email
    %td Заказов: 0
    %td На сумму: 1 145 084
    %td Визитов: 84
    %td Последний: 12.04.2012
    %td.arrow_cel
    -#%td<= link_to 'Edit', edit_admin_user_path(user)
    -#%td<= link_to 'Destroy', admin_user_path(user), confirm: 'Are you sure?', method: :delete

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.haml
=content_for :head do
  :javascript
    function scroll_load() {
      $('#o').val( $('.user_list tbody tr').length )
      $('#search_form').submit()
    }
    function complete_field(f) {
      var text = f.val()
      $('.user_list tbody').html('')
      if(text.length > 1) {
        $('#search_form').submit()
      }
    }
    $(function() {
      $('#user_search').keydown(function(e) {
        switch(e.keyCode) {
          case 13: //return
          case 27: // escape
            e.preventDefault()
        }
      }).keyup(function(e) {
        switch(e.keyCode) {
          case 35: // end
          case 36: // home
          case 16: // shift
          case 17: // ctrl
          case 18: // alt
          case 37: // left
          case 39: // right
            break
          default:
            complete_field($(this))
        }
      }).focus()
      $('#search_form').on('ajax:success', function (xhr, data) {
        $('.user_list tbody').html( $('.user_list tbody').html() + data )
      })
      $('#user_sort').on('change', function() {
        $('.user_list tbody').html('')
        scroll_load()
      })
      $('.sort_link').on('click', function() {
        $('#sort_desc').val( $('#sort_desc').val() == '0' ? '1' : '0' )
        $('.user_list tbody').html('')
        scroll_load()
        return false
      })
      $(window).scroll(function() {
        if($(window).scrollTop() == $(document).height() - $(window).height()) {
          scroll_load()
        }
      })
    })
-#= link_to 'Добавить пользователя', new_admin_user_path

%h1
  Поиск Пользователей
  -unless params[:all]
    %a{:href => "#{admin_users_path(:all => true)}"} Показать всех &nbsp;&nbsp;( #{User.count} )
/ // admin page
.admin_form
  =form_tag admin_users_path, :method => :get, :id => 'search_form', :remote => true do
    -unless params[:all]
      =text_field_tag :q, nil,
        :class => 'search-field',
        :id => 'user_search',
        :value => "Начните вводить имя или e-mail пользователя",
        :onblur => "if (this.value=='') {this.value='Начните вводить имя или e-mail пользователя'; this.className='search-field';}",
        :onfocus => "if (this.value=='Начните вводить имя или e-mail пользователя') {this.value=''; this.className='selected'}",
        :autocomplete => 'off'
    -else
      %span.sort Сортировать по:
      .lineForm3
        =hidden_field_tag :l, @default_limit
        =hidden_field_tag :o, 0
        =hidden_field_tag :sort_desc, 0
        %select#user_sort{:tabindex => "2", :name => 'user_sort' }
          %option{:value => ""} -
          %option{:value => "fio"} ФИО
          %option{:value => "email"} E-mail
      %a.sort_link{:href => "#"}
        =image_tag "sort_icon.png"
.user_list
  %table
    %thead
      %tr
        %th
          %th{:style => 'text-transform:uppercase'}
        %th
        %th
        %th
        %th
        %th
    %tbody
      =render :partial => 'admin/users/searchresults', :locals => { :users => @users }
  -#%div
    %small
      Всего найдено пользователей: #{users.size}

app/views/admin/users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.haml
%h1= @user.fio
.u_options
  %a.u_active_link.field1{:href => "#"} Информация
  %a.field2{:href => "#"} Размеры
  %a.field3{:href => "#"} Заказы
/ // CONTENT
.user_admin
  .customScrollBox
    #field1
      %dl
        %dt Ф.И.О.
        %dd= @user.fio
      %dl
        %dt Электронная почта
        %dd= @user.email
      %dl
        %dt Телефон
        %dd= @user.phone
      -#
        %dl
          %dt Карта клиента №
          %dd 1375 737
        %dl
          %dt Баллы программы
          %dd 5760
        %dl
          %dt Программа лояльности
          %dd Статус 1
        %dl
          %dt Статус в рассылке
          %dd Активен
        %dl
          %dt Профили в соцсетях
          %dd
            %img{:alt => "", :src => "fb.png"}/
        %dl
          %dt Комментарии
          %dd Нет
        %dl
          %dt Визитов
          %dd 45
        %dl
          %dt Последний визит
          %dd 12.09.2011
    #field2{:style => "display:none;"}
      .u_title размеры
      .u_create_profile
        %a{:href => "#"} создать новый профайл
      %table.u_table
        %thead
          %tr
            %th профайл
            %th создан
            %th Статус
            %th
        %tbody
          %tr
            %td
              %a.u_close{:href => "#"}
              %a.u_size{:href => "#"} Размеры для рубашки
            %td 21.10.2011
            %td Неактивный
            %td
              %a{:href => "#"} изменить
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "4"}
              .u_more
                %div
                  Обхват шеи
                  %span 23 см
                %div
                  Обхват груди
                  %span 112 см
                %div
                  Обхват талии
                  %span 76 см
                %div
                  Обхват бедер
                  %span 87 см
                %div
                  Ширина спины
                  %span 50 см
                %div
                  Длина спины до талии
                  %span 98 см
                %div
                  Ширина плеча
                  %span 43 см
                %div
                  Длина рукава
                  %span 65 см
                %div
                  Обхват запястья
                  %span 15 см
          %tr
            %td
              %a.u_close{:href => "#"}
              %a.u_size{:href => "#"} Размеры для костюма, брюк, пальто и пиджака
            %td 21.10.2011
            %td Неактивный
            %td
              %a{:href => "#"} изменить
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "4"}
              .u_more
                %div
                  Обхват шеи
                  %span 23 см
                %div
                  Обхват груди
                  %span 112 см
                %div
                  Обхват талии
                  %span 76 см
                %div
                  Обхват бедер
                  %span 87 см
                %div
                  Ширина спины
                  %span 50 см
                %div
                  Длина спины до талии
                  %span 98 см
                %div
                  Ширина плеча
                  %span 43 см
                %div
                  Длина рукава
                  %span 65 см
                %div
                  Обхват запястья
                  %span 15 см
          %tr
            %td
              %a.u_close{:href => "#"}
              %a.u_size{:href => "#"} Размеры для рубашки
            %td 21.10.2011
            %td Неактивный
            %td
              %a{:href => "#"} изменить
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "4"}
              .u_more
                %div
                  Обхват шеи
                  %span 23 см
                %div
                  Обхват груди
                  %span 112 см
                %div
                  Обхват талии
                  %span 76 см
                %div
                  Обхват бедер
                  %span 87 см
                %div
                  Ширина спины
                  %span 50 см
                %div
                  Длина спины до талии
                  %span 98 см
                %div
                  Ширина плеча
                  %span 43 см
                %div
                  Длина рукава
                  %span 65 см
                %div
                  Обхват запястья
                  %span 15 см
          %tr
            %td
              %a.u_close{:href => "#"}
              %a.u_size{:href => "#"} Размеры для костюма, брюк, пальто и пиджака
            %td 21.10.2011
            %td Неактивный
            %td
              %a{:href => "#"} изменить
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "4"}
              .u_more.u_status
                %div
                  Обхват шеи
                  %span 23 см
                %div
                  Обхват груди
                  %span 112 см
                %div
                  Обхват талии
                  %span 76 см
                %div
                  Обхват бедер
                  %span 87 см
                %div
                  Ширина спины
                  %span 50 см
                %div
                  Длина спины до талии
                  %span 98 см
                %div
                  Ширина плеча
                  %span 43 см
                %div
                  Длина рукава
                  %span 65 см
                %div
                  Обхват запястья
                  %span 15 см
    #field3{:style => "display:none;"}
      .u_title история и статус заказов
      .u_subtitle заказы в работе
      %table.u_table.zakaz
        %thead
          %tr
            %th № Заказа
            %th дата заказа
            %th Предполагаемая дата доставки
            %th сумма
        %tbody
          %tr
            %td
              %a.u_size{:href => "#"} 10000770
            %td 05.11.2011
            %td 13.01.2012
            %td
              %span.u_price
                189 000
                %span.rur
                  p
                  %span уб.
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "4"}
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img1.jpg')}"}
                  %a.u_size{:href => "#"} Пиджак
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img2.jpg')}"}
                  %a.u_size{:href => "#"} Брюки
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img3.jpg')}"}
                  %a.u_size{:href => "#"} Ремень
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
                %tr
            %td
              %a.u_size{:href => "#"} 10000770
            %td 05.11.2011
            %td 13.01.2012
            %td
              %span.u_price
                189 000
                %span.rur
                  p
                  %span уб.
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "4"}
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img1.jpg')}"}
                  %a.u_size{:href => "#"} Пиджак
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img2.jpg')}"}
                  %a.u_size{:href => "#"} Брюки
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img3.jpg')}"}
                  %a.u_size{:href => "#"} Ремень
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
      %br
      .u_subtitle закрытые заказы
      %table.u_table.reviews
        %thead
          %tr
            %th № Заказа
            %th дата заказа
            %th дата доставки
            %th отзыв
            %th сумма
        %tbody
          %tr
            %td
              %a.u_size{:href => "#"} 10000770
            %td 05.11.2011
            %td 13.01.2012
            %td отзыв
            %td
              %span.u_price
                189 000
                %span.rur
                  p
                  %span уб.
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "5"}
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img1.jpg')}"}
                  %a.u_size{:href => "#"} Пиджак
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img2.jpg')}"}
                  %a.u_size{:href => "#"} Брюки
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img3.jpg')}"}
                  %a.u_size{:href => "#"} Ремень
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
                %tr
            %td
              %a.u_size{:href => "#"} 10000770
            %td 05.11.2011
            %td 13.01.2012
            %td
              %img{:src => "#{asset_path('black_star.png')}"}
              %img{:src => "#{asset_path('black_star.png')}"}
              %img{:src => "#{asset_path('black_star.png')}"}
              %img{:src => "#{asset_path('black_star.png')}"}
              %img{:src => "#{asset_path('grey_star.png')}"}
            %td
              %span.u_price
                189 000
                %span.rur
                  p
                  %span уб.
          %tr.hidden{:style => "display:none;"}
            %td{:colspan => "5"}
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img1.jpg')}"}
                  %a.u_size{:href => "#"} Пиджак
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img2.jpg')}"}
                  %a.u_size{:href => "#"} Брюки
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.
              .u_more.u_status
                %div
                  %img{:src => "#{asset_path('u_img3.jpg')}"}
                  %a.u_size{:href => "#"} Ремень
                  %span.u_price
                    189 000
                    %span.rur
                      p
                      %span уб.