config/routes.rb
Bns::Application.routes.draw do
  resources :articles

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  devise_for :users, :skip => [:registrations], :controllers => { :confirmations => "confirmations" }

  namespace :admin do
    root :to => 'home#index'
    resources :fabrics
    resources :accessories
    resources :articles, :except => [:new,:destroy] do
      post 'preview', :on => :collection
    end
    resources :users
    resources :shops do
      get 'day_measures', :on => :member
    end
    post 'shop_measure_setbusy' => "shop_measure#set_busy"
    post 'shop_measure_set_username' => "shop_measure#set_username"
  end

  namespace :buy do
    %w(suit jacket trousers shirt coat).each do |cloth|
      get "#{cloth}(/:step)" => "#{cloth}#index", :as => "#{cloth}"
      get "select_#{cloth}_fabric/:id" => "#{cloth}#select_fabric"
      post "select_#{cloth}_design" => "#{cloth}#select_design"
    end
  end

  get "about" => "home#about"
  get "profile" => "home#profile"
  get "shop" => "shop#index"
  get "shop/sizing_table" => "shop#sizing_table"
  post "shop/book_hour" => "shop#book_hour"
  get "faq" => "home#faq"
  get "gift_certificates" => "home#gift_certificates"
  get "quality_guarantee" => "home#quality_guarantee"
  get "material" => "home#material"
  get "process" => "home#process"
  get "buy_online" => "home#buy_online"

  get "content/:p1(/:p2)" => "home#content"

  root :to => 'home#index'

end

app/views/layouts/admin.html.haml
!!!
%html{:lang => "ru", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "IE=7", "http-equiv" => "X-UA-Compatible"}/
    %title BOND&amp;STINSON
    = stylesheet_link_tag    "application", :media => "all"
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js", :type => "text/javascript"}
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"}
    = javascript_include_tag "application"
    /[if lte IE 7.0]
      <link href="#{asset_path('ie.css')}" rel="stylesheet" type="text/css" />
    /[if lt IE 7.0]
      <script src="#{asset_path('DD_belatedPNG_0.0.8a.js')}" type="text/javascript"></script>
      <script type="text/javascript">
      DD_belatedPNG.fix('img, .logo, .new_coll, .new_coll a');
      </script>
    %noscript
      :css
        #mcs3_container .customScrollBox{overflow:auto;}
        #mcs3_container .dragger_container{display:none;}
    = yield :head
  %body
    /
      <img src="slides/slide3.jpg" alt="" id="bgimg">
    / // PAGE
    .page
      / // HEADER
      .header_container.administrator
        .header_inner
          %a.logo{:href => "#", :title => "BOND&amp;STINSON"}
          / tools
          / menu
          - c = controller.controller_name
          %ul.nav_menu
            %li{ :class => "users".eql?(c) ? 'current_menu' : '' }
              %a{:href => admin_users_path} пользователи
            %li{ :class => "shops".eql?(c) ? 'current_menu' : '' }
              %a{:href => admin_shops_path} магазины
            %li{ :class => ["fabrics"].include?(c) ? 'current_menu' : '' }
              %a{:href => admin_fabrics_path} ткани
            %li{ :class => "accessories".eql?(c) ? 'current_menu' : '' }
              %a{:href => admin_accessories_path} аксессуары
            %li{ :class => "articles".eql?(c) ? 'current_menu' : '' }
              %a{:href => admin_articles_path} тексты
          -if ["fabrics"].include?(c)
            %ul.nav_menu.submenu
              %li{ :class => params[:kind].nil? && params[:element].nil? ? 'current_menu' : '' }
                %a{:href => admin_fabrics_path} Все
              %li{ :class => params[:kind].nil? && params[:element] == 'cloth' ? 'current_menu' : '' }
                %a{:href => admin_fabrics_path(:element => :cloth)} Основные
              %li{ :class => params[:kind].nil? && params[:element] == 'lining' ? 'current_menu' : '' }
                %a{:href => admin_fabrics_path(:element => :lining)} Подкладки
              %li{ :class => params[:kind] == 'shirt' ? 'current_menu' : '' }
                %a{:href => admin_fabrics_path(:kind => :shirt)} Рубашки
              %li{ :class => params[:kind] == 'coat' && params[:element] == 'cloth' ? 'current_menu' : '' }
                %a{:href => admin_fabrics_path(:kind => :coat, :element => :cloth)} Основные пальто
              %li{ :class => params[:kind] == 'coat' && params[:element] == 'lining' ? 'current_menu' : '' }
                %a{:href => admin_fabrics_path(:kind => :coat, :element => :lining)} Подкладки пальто
          %span{:style => "color: white"}
            =notice
            =alert
      / HEADER //
      .clear_container
        = yield

app/views/layouts/application.html.haml
!!!
%html{:lang => "ru", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "IE=7", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "SKYPE_TOOLBAR_PARSER_COMPATIBLE", "name" => "SKYPE_TOOLBAR"}/

    %title BOND &amp; STINSON
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    "application", :media => "all"
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js", :type => "text/javascript"}
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"}
    = javascript_include_tag "application"
    /[if lte IE 7.0]
      <link href="#{asset_path('ie.css')}" rel="stylesheet" type="text/css" />
    /[if lt IE 7.0]
      <script src="#{asset_path('DD_belatedPNG_0.0.8a.js')}" type="text/javascript"></script>
      <script type="text/javascript">
      DD_belatedPNG.fix('img, .logo, .new_coll, .new_coll a');
      </script>
    -if flash[:confirmed]
      :javascript
          $(document).ready(function() {
            $('#welcome').fancybox().trigger('click');
          });
    %noscript
      :css
        #mcs3_container .customScrollBox{overflow:auto;}
        #mcs3_container .dragger_container{display:none;}
    = yield :head
  %body
    = yield :bg_slide
    / // PAGE
    .page
      / // HEADER
      .header_container
        .header_inner
          %a.logo{:href => "#{root_path}", :title => "BOND &amp; STINSON"}
          / tools
          .account
            %ul.auth
              %li.a1
                -if user_signed_in?
                  .m_close.exit{:title => "Выход"}
                  %a{:href => "#"} #{current_user.fio}
                -else
                  %a{:href => "#"} мой аккаунт
                / auth form
                .auth_form{:style => "display:none;"}
                  -if user_signed_in?
                    .m_menu
                      %a{:href => "#{profile_path}"} мой аккаунт
                      %a{:href => "#"} история и статус заказов
                      %a{:href => "#"} мои размеры
                      %a{:href => "#"} программа лояльности

                      =button_to 'Выйти', destroy_user_session_path, :method => :delete, :class => "exit_btn"
                  -else
                    %a.reg{:href => "#registration", :tabindex => "4"} создать аккаунт
                    = link_to "забыли пароль?", "#forgot_password", {:class => "forgot"}
                    /new_password_path(resource_name) tests -  #change_password, #welcome/
                    .form_inner
                      %p.title Мой bond &amp; stinson
                      .error_explanation
                        %ul
                      =form_tag session_path(resource_name), :remote => true, :format => :json, :id => 'sign_in' do
                        %label{:for => "sign_email"} Ваша&nbsp;электронная&nbsp;почта:
                        =text_field_tag "user[email]", nil, :tabindex => "1", :id => "sign_email"
                        %label{:for => "sign_pwd"} Ваш пароль:
                        =password_field_tag "user[password]", nil, :tabindex => "2", :id => "sign_pwd"
                        .submit_btn
                          %input#submit{:tabindex => "3", :type => "submit", :value => "Войти"}/
                      .create_account
                    
              %li.current_menu
                %a{:href => "#"} корзина(0)
          / if current user
          /  <div class="account">
          /   <ul class="auth">
          /     <li class="a1">
          /       <div class="m_close"></div>
          /       <a href="#">Виктор</a>
          /       <div class="auth_form" style="display:none;">
          /         <div class="m_menu">
          /           <a href="#" >мой аккаунт</a>
          /           <a href="#" >история и статус заказов </a>
          /           <a href="#" >мои размеры</a>
          /           <a href="#" >программа лояльности</a>
          /       </div>
          /       </div>
          /     </li>
          /     <li class="current_menu"><a href="#">корзина(0)</a></li>
          /   </ul>
          /  </div>
          / menu
          - cn = controller.controller_name
          - an = controller.action_name
          %ul.nav_menu
            %li
              %a#buy{:href => "#{buy_online_path}"} купить онлайн
            %li{ :class => cn == "shop" ? 'current_menu' : '' }
              %a{:href => "#{shop_path}"} магазины
            -#%li
              %a{:href => "#"} коллекции
            %li{ :class => an == "quality_guarantee" ? 'current_menu' : '' }
              %a{:href => "#{quality_guarantee_path}"} качество
            %li{ :class => an == "gift_certificates" ? 'current_menu' : '' }
              %a{:href => "#{gift_certificates_path}"} подарки &amp; Скидки
            %li{ :class => an == "about" ? 'current_menu' : '' }
              %a{:href => "#{about_path}"} о компании
          %ul.nav_menu.submenu{:style => "display:none;"}
            %li
              %a{:href => "#"} костюмы
            %li
              %a{:href => "#"} Пиджаки
            %li
              %a{:href => "#"} Брюки
            %li
              %a{:href => "#"} сорочки
            %li
              %a{:href => "#"} пальто
            %li
              %a{:href => "#"} аксессуары
          %span.notice_alert
            =notice
            =alert
      / HEADER //
      / // CONTENT
      = yield
      / CONTENT //
      / // FOOTER
      .footer
        .footer_inner
          %ul.contacts
            %li.mailer_btn
              %a{:href => "#"} рассылка
            %li.contacts_btn
              %a{:href => "#"} контакты
            %li.current_menu
              %span.phone +7 (495) 384-22-54
            -#%li.current_menu
              %a{:href => "#"}
                =image_tag "fb2.png"

        / mailer form
        .mailer_form{:style => "display:none;"}
          %p.title подписаться на рассылку
          %form{:action => "", :method => "GET", :name => ""}
            %label{:for => "mailer_email"} Введите ваш e-mail:
            %input#mailer_email{:tabindex => "1", :type => "text"}/
            .submit_btn
              %input#submit{:tabindex => "2", :type => "submit", :value => "Подписаться", :class => "subscribe"}/
              %input#submit{:tabindex => "3", :type => "submit", :value => "Отписаться", :class => "non_subscribe"}/
            
          -# successful sending
          -#%p.title спасибо
          -#%p.sending Мы будем информировать Вас обо всех акциях и новинках
        / contacts form
        .contacts_form{:style => "display:none;"}
          =image_tag "map.png"
          .contacts_info
            %p.title наши Контакты
            %p
              Саввинская набережная, 11
              %br/
              Москва, 19505
            %p
              %span Тел.:
              +7 (495) 540-42-77
            %p
              E-mail:
              %a{:href => "mailto:info@bond-stinson.ru"} info@bond-stinson.ru
            %p.my_shop
              %a{:href => "#{shop_path}"} Наши магазины
      / FOOTER //
    / PAGE //
/ REGISTRATION FORM
#registration.registration{:style => "display:none;"}
  /registration form
  .reg_form.hidden_shadow
    %p.hint{:style =>"margin-bottom:0px; display:none;"}
      Вам отправлено письмо
      %br/
      с кодом подтверждения.
    .reg_block
      .error_explanation
        %ul
      %p.title регистрация
      =form_tag user_registration_path, :remote => true, :format => :json, :id => 'new_user' do
        %label{:for => "reg_fio"} имя и фамилия:
        %label{:for => "reg_email"} e-mail:
        .clear
        =text_field_tag "user[fio]", nil, :tabindex => "1", :id => "reg_fio", :class => "reg_input"
        =text_field_tag "user[email]", nil, :tabindex => "1", :id => "reg_email"
        %br/
        %label{:for => "reg_phone"} контактный телефон:
        %label{:for => "reg_password"} пароль:
        .clear
        =text_field_tag "user[phone]", nil, :tabindex => "2", :id => "reg_phone", :class => "reg_input"
        =password_field_tag "user[password]", nil, :tabindex => "4", :id => "reg_password"
        .all_reg_errors
        .submit_btn
          %input#submit{:type => "submit", :value => "создать аккаунт", :tabindex => "5"}/


/ Forgot your password?
#forgot_password.registration{:style => "display:none"}
  /forgot password form
  .reg_form.hidden_shadow
    .error_explanation
      %ul
    %p.title забыли пароль?
    -#=form_tag user_registration_path, :remote => true, :format => :json, :id => 'new_user' do
    =form_for(User.new, :as => 'user', :url => password_path('user'), :remote => true, :html => { :method => :post }) do |f|
      %p.hint
        Пожалуйста, введите ваш e-mail и
        %br
        мы направим Вам инструкцию по
        %br
        восстановлению Вашего пароля
      %label{:for => "forgot_email"} e-mail:
      .clear
      = f.text_field :email, :tabindex => "1", :id => "forgot_email"
      .submit_btn.sub_hint
        %input#submit{:type => "submit", :value => "отправить", :tabindex => "2"}/
    .compl{:style => "display:none"}
      %p.title спасибо
      %p.hint
        Инструкции&nbsp;по&nbsp;восстановлению&nbsp;пароля 
        %br
        отправлена на вашу электронную 
        %br
        почту.
      %p.hint{:style => "margin-bottom:0px;"}
        %a{ :href => root_path } На главную


/ Welcome to the site
#welcome.registration{:style => "display:none"}
  .reg_form.hidden_shadow
    .compl
      %p.title Добро пожаловать
      %p.hint{:style => "margin-bottom:0px;"}
        Ваш аккаунт подтверждён.



app/views/layouts/preview.html.haml
!!!
%html{:lang => "ru", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "IE=7", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "SKYPE_TOOLBAR_PARSER_COMPATIBLE", "name" => "SKYPE_TOOLBAR"}/

    %title BOND &amp; STINSON
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    "application", :media => "all"
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js", :type => "text/javascript"}
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"}
    = javascript_include_tag "application"
    /[if lte IE 7.0]
      <link href="#{asset_path('ie.css')}" rel="stylesheet" type="text/css" />
    /[if lt IE 7.0]
      <script src="#{asset_path('DD_belatedPNG_0.0.8a.js')}" type="text/javascript"></script>
      <script type="text/javascript">
      DD_belatedPNG.fix('img, .logo, .new_coll, .new_coll a');
      </script>
    -if flash[:confirmed]
      :javascript
          $(document).ready(function() {
            $('#welcome').fancybox().trigger('click');
          });
    %noscript
      :css
        #mcs3_container .customScrollBox{overflow:auto;}
        #mcs3_container .dragger_container{display:none;}
  %body
    .page
      = yield